### ISSUE TITLE
<CR> bug

### ISSUE THREAD

**Issue by kovetskiy** [ervandew/matchem#10]
![example](https://cloud.githubusercontent.com/assets/8445924/7002999/07775fc6-dc43-11e4-8817-a3f1a8da877b.gif)

**Comment by seletskiy** [comment]
Actually, not bounded to UltiSnips.

Bug is reproduceable with following typeset:

```
{1<Delete><CR>
```

**Comment by ervandew** [comment]
This also isn't tied to the `<cr>` mapping either. This can also be reproduced using simply:

    {1<del><esc>

I've fixed the `<del>` mapping, but I haven't yet tested if this fixes the UltiSnips case yet or not. @kovetskiy: can you see if the lastest matchem version works properly with ultisnips now?

**Comment by kovetskiy** [comment]
@ervandew last version fix your and @seletskiy problems, but not fix my problem. And I can reproduce problem without UltiSnips.
```
['b<C-J><ESC>j
```

Aand now I cannot remove closing bracked `]` with backspace.
```test[<ESC>A``` and try to backspace.

**Comment by ervandew** [comment]
I can reproduce the first problem but not the second.

For the first one, what behavior do you expect when using `<c-j>` at that position? Do you want the closing delimiters to remain on the current line or move to the new line? Is ultisnips using `<c-j>` internally, or is that just something you use manually?

**Comment by kovetskiy** [comment]
@ervandew it this case I'm used clear vim with only matchem plugin and `set nocompatible`.

**Comment by ervandew** [comment]
What about my other questions?

**Comment by kovetskiy** [comment]
@ervandew `<C-J>` should has behavior same as `<CR>`. In my last cases I don't used UltiSnips, and no, UltiSnips doesn't use `<C-J>` internally.

**Comment by ervandew** [comment]
> Aand now I cannot remove closing bracked `]` with backspace.
`test[<ESC>A` and try to backspace.
> it this case I'm used clear vim with only matchem plugin and `set nocompatible`.

Try adding `set backspace+=start` as well, otherwise you are using vi compatible backspacing, which doesn't allow you to backspace past the start of the current insert.

**Comment by ervandew** [comment]
Latest commit adds support for `<nl>` (`<c-j>`).

**Comment by kovetskiy** [comment]
Hi, I've found yet another bug.
I have this mapping:
``` inoremap <C-A> <C-O>A ```
Then I do:
```[<C-A><ESC>```
After `<ESC>` matchem insert extra `]`.

**Comment by ervandew** [comment]
@kovetskiy 
That mapping bypasses matchem completely. Try using `imap` instead of `inoremap` instead so that matchem can be involved:

    imap <c-a> <c-o>A

**Comment by kovetskiy** [comment]
@ervandew Ok, I got it, thank you! :+1:

**Comment by seletskiy** [comment]
@ervandew: Hi! I found another bug:

```
["|"]   press <Right>
[""]|
```

**Comment by kovetskiy** [comment]
@ervandew Hi! I found another bug:
matchem does not work properly with vim abbreviations.
`ab if( if (`
```
if(
```
and I got:
`if ( [cursor]))`
